### ISSUE TITLE
Width and height below 80dp visual bug.

### ISSUE THREAD

**Issue by jwv** [CoXier/CheckBox#1]
Hi,

When u change the layout_width and layout_height below 80dp u get visual bug.

Thx.

**Comment by CoXier** [comment]
I am late for this issue.

You should set `tick_width` and `border_width` like this:

```java
    <com.uniquestudio.library.CircleCheckBox
        android:id="@+id/circle_check_box"
        android:layout_width="80dp"
        android:layout_height="80dp"
        android:layout_gravity="center_vertical"
        android:layout_marginLeft="100dp"
        app:border_width="4dp"
        app:tick_width="6dp"/>
```

**Comment by sarthakps** [comment]
The issue still seems to be there. A white dot appears at the top left corner of the layout.

<com.uniquestudio.library.CircleCheckBox
        android:id="@+id/item_todos_checkbox"
        android:layout_width="30dp"
        android:layout_height="30dp"
        app:background_color="@color/transparent"
        app:animation_duration="100"
        app:border_color="@color/white"
        app:tick_color="@color/white"
        app:border_width="2dp"
        app:tick_width="2dp"/>
