### ISSUE TITLE
how to mark checked initially ?

### ISSUE THREAD

**Issue by shubhamsardar07** [CoXier/CheckBox#2]
is it possible to set it checked initially pragmatically , without clicking on it?

**Comment by mosi5505** [comment]
Hi dear
This is my issue too.

**Comment by mosi5505** [comment]
Hi Dear

Chk_Learn = (CircleCheckBox) findViewById(R.id.checkBoxLearn);
Chk_Learn.post(new Runnable() {
            @Override
            public void run() {
                    Chk_Learn.setChecked(true);
            }
        });

use this in oncreate method of activity...

**Comment by CoXier** [comment]
Sorry this issue have not be solved yet.
@mosi5505 This solution seems not to be suitable.I will fix it next release version.

**Comment by CoXier** [comment]
I fixed this issue just now.

Now you can define `app:checked="true"` in layou xml file.

```java
    <com.uniquestudio.library.CircleCheckBox
        app:checked="true"
        android:id="@+id/circle_check_box"
        android:layout_width="150dp"
        android:layout_height="150dp"
        android:layout_gravity="center_vertical"
        android:layout_marginLeft="100dp"/>
```
